version: '3.7'
services:
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
volumes:
  db: