name: pr-agent

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR Agent
    if: ${{ github.event.sender.type != 'Bot' }}
    steps:
      - id: pr-agent
        uses: Codium-ai/pr-agent@v0.2
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI.ORG: ${{ secrets.OPENAI_ORG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}